#!/bin/bash

set -euo pipefail

# Create metadata and upload output files

usage() {
cat << EOF

	Create metadata files and upload workflow outputs
	Usage: $0 -b billing_project -d destination_bucket -i workflow_info -o output_file

	OPTIONS
		-h	Display this message and exit
		-b	Billing project to use for file upload
		-d	Destination bucket/path to upload output files and metadata to
		-i	Workflow info: TSV containing run_timestamp, workflow_name, workflow_version
		-o	Output file to upload. This option can be selected multiple times.

EOF
}

while getopts "hb:d:i:o:" OPTION; do
	case ${OPTION} in
			h) usage; exit;;
			b) BILLING_PROJECT="${OPTARG}";;
			d) DESTINATION_PATH="${OPTARG%/}/";;
			i) WORKFLOW_INFO="${OPTARG}";;
			o) OUTPUT_FILES+=("${OPTARG}");;
			\?) usage; exit 1;;
	esac
done

if [[ -z "${BILLING_PROJECT:-}" ]]; then
	usage
	echo "[ERROR] Must provide -b billing project"
	exit 1
fi

if [[ -z "${DESTINATION_PATH:-}" ]]; then
	usage
	echo "[ERROR] Must provide -d destination_path"
	exit 1
fi

if [[ -z "${WORKFLOW_INFO:-}" ]]; then
	usage
	echo "[ERROR] Must provide -i workflow_info"
	exit 1
fi

if [[ -z "${OUTPUT_FILES:-}" ]]; then
	usage
	echo "[ERROR] Must provide at least one -o output_file"
	exit 1
fi

for output_file in "${OUTPUT_FILES[@]}"; do
	md5_hash=$(md5sum "${output_file}" | awk '{print $1}' | xxd -r -p | base64)

	paste \
		<(basename "${output_file}") \
		<(echo "${md5_hash}")
		"${WORKFLOW_INFO}" \
	> "${output_file}.meta.tsv"

	echo "${output_file}" >> output_files.txt
	echo "${output_file}.meta.tsv" >> output_files.txt
done

gsutil \
	-u "${BILLING_PROJECT}" \
	-m cp \
	-I \
	"${DESTINATION_PATH}" \
< output_files.txt
