#!/bin/bash
#
# Run data integrity tests and promote data in staging buckets to production

set -eEuo pipefail

usage() {
cat << EOF

  Run data integrity tests and promote data in staging buckets to production.

  $(tput bold)[CAUTION] This also deletes data in the production bucket that is not found in the staging bucket.$(tput sgr0)

  Usage: $0 [OPTIONS]

  OPTIONS
  ───────
    $(tput bold)-h$(tput sgr0)  Display this message and exit
    $(tput bold)-t$(tput sgr0)  Comma-separated set of teams to promote data for
    $(tput bold)-a$(tput sgr0)  Promote all teams' data
    $(tput bold)-l$(tput sgr0)  List available teams
    $(tput bold)-p$(tput sgr0)  Promote data. If this option is not selected, data that would be copied or deleted is printed out, but files are not actually changed (dry run)
    $(tput bold)-s$(tput sgr0)  Staging bucket type; options are 'uat' or 'dev' ['uat']

EOF
}

log() {
  echo -e "$(tput bold)$(tput setaf 110)[$(date +'%Y-%m-%d %H:%M:%S')] $*$(tput sgr0)" >&1
}

err() {
  echo -e "$(tput bold)$(tput setaf 203)[$(date +'%Y-%m-%d %H:%M:%S')]: $*$(tput sgr0)" >&2
}

list_teams() {
  echo "$(tput bold)Available teams:$(tput sgr0)"
  echo "${ALL_TEAMS[@]}" | tr ' ' '\n'
}

non_empty_check() {
  source_path="${1#/}/**"

  file_list_sorted=$(gsutil ls -l "${source_path}" | sort -n -k 1 | grep -E '^[0-9[:space:]]')

  while read -r file_size timestamp gs_uri; do
    if [[ $file_size -le 10 ]]; then
      err "Found a file less than or equal to 10 bytes: [$gs_uri]"
      exit 1
    fi
  done <<< "${file_list_sorted}"
}

metadata_check() {
  source_path="${1#/}/**"

  file_list=$(gsutil ls -l "${source_path}" | awk '{print $3}' | grep '^gs://')
  subfolder_paths=$(echo "${file_list}" | grep "MANIFEST.tsv$" | awk -F 'MANIFEST.tsv' '{print $1}')

  while read -r gs_path; do
    files_to_check=$(echo "${file_list}" | grep $gs_path | grep -v "MANIFEST.tsv$" | sed "s;$gs_path;;")
    files_in_manifest=$(gsutil cat "${gs_path}MANIFEST.tsv" | tail -n +2)
    while read -r file; do
      files_exist=$(echo "$files_in_manifest" | grep "$file" || [[ $? == 1 ]])
      if [[ -z "$files_exist" ]]; then
        err "File does not have associated metadata and is absent from MANIFEST: [${gs_path}${file}]"
        exit 1
      fi
    done <<< "${files_to_check}"
  done <<< "${subfolder_paths}"
}

gsync() {
  source_path="${1#/}/"
  destination_path="${2#/}/"

  # shellcheck disable=SC2086
  gsutil -m rsync \
    -d \
    -r \
    ${DRY_RUN_ARG} \
    "${source_path}" \
    "${destination_path}"
}

ALL_TEAMS=(cohort team-hafler team-hardy team-jakobsson team-lee team-scherzer team-sulzer team-voet team-wood)

# Default to dry run if promotion is not selected
DRY_RUN_ARG="-n"
# Default to dev staging buckets
STAGING_BUCKET_TYPE='uat'

while getopts "ht:alps:" OPTION; do
  case $OPTION in
    h) usage; exit ;;
    t) read -ra TEAMS <<< "$(echo "${OPTARG}" | tr ',' ' ')" ;;
    a) TEAMS=( "${ALL_TEAMS[@]}" ) ;;
    l) list_teams; exit ;;
    p) DRY_RUN_ARG="" ;;
    s) STAGING_BUCKET_TYPE=${OPTARG} ;;
    \?) usage; exit ;;
  esac
done

if [[ -z "${TEAMS:-}" ]]; then
  usage
  list_teams
  exit
fi

if [[ "${STAGING_BUCKET_TYPE}" != "uat" ]] | [[ "${STAGING_BUCKET_TYPE}" != "dev" ]] ; then
  usage
  err "Staging bucket type must be 'uat' or 'dev'"
  exit 1
fi

# Confirm that the teams provided are valid
for team in "${TEAMS[@]}"; do
  if [[ ! "${ALL_TEAMS[*]}" =~ ${team} ]]; then
    err "Team [${team}] is not one of the available teams"
    list_teams
    exit 1
  fi
done

# Check that files are not empty and are not less than or equal to 10 bytes (factoring in white space)
for team in "${TEAMS[@]}"; do
  staging_bucket=gs://asap-${STAGING_BUCKET_TYPE}-data-${team}

  non_empty_check \
    "${staging_bucket}"
done

# Check that files have associated metadata and is present in MANIFEST.tsv
for team in "${TEAMS[@]}"; do
  staging_bucket=gs://asap-${STAGING_BUCKET_TYPE}-data-${team}

  metadata_check \
    "${staging_bucket}"
done

log "All tests have passed"

# Try syncing staging data to production
for team in "${TEAMS[@]}"; do
  staging_bucket=gs://asap-${STAGING_BUCKET_TYPE}-data-${team}
  production_bucket=gs://asap-curated-data-${team}

  log "Promoting [${team}] data to production"
  log "\tStaging bucket:\t\t[${staging_bucket}]"
  log "\tProduction bucket:\t[${production_bucket}]"

  gsync \
    "${staging_bucket}" \
    "${production_bucket}"
done
